// Generated by node scripts/build-slack-dashboard.mjs.
// Replace the entire slack-spend dashboard function with this file.
import { createClient } from 'npm:@supabase/supabase-js@2.117.1';
const HELP = 'Try /spend 12.50 · /spend 5.50 2026-10-05 · /spend refund 5 · /spend undo · /spend total · /spend standings · /spend done 2026-10-14. All purchases count toward Coffee shop. No category is needed. Amounts add to your total; do not submit your cumulative balance.';
function parseCommand(text) {
  const parts = text.trim().split(/\s+/).filter(Boolean);
  if (!parts.length || parts[0] === 'help') return { action: 'help' };
  if (parts[0] === 'total' && parts.length === 1) return { action: 'total' };
  if (parts[0] === 'standings') {
    if (parts.length !== 1) throw new Error('Use /spend standings to see the group’s October spending.');
    return { action: 'standings' };
  }
  if (parts[0] === 'undo' && parts.length <= 2) {
    if (parts[1] && !/^[0-9a-f-]{36}$/i.test(parts[1])) throw new Error('Use /spend undo, or /spend undo followed by an entry ID.');
    return { action: 'undo', entry_id: parts[1] || null };
  }
  if (parts[0] === 'invite' && parts.length === 2) {
    const match = /^(?:<@)?([UW][A-Z0-9]{2,})(?:\|[^>]+)?>?$/.exec(parts[1]);
    if (!match) throw new Error('Use /spend invite @person, selecting a Slack member.');
    return { action: 'invite', slack_user_id: match[1] };
  }
  if (parts[0] === 'done' && parts.length <= 2) return { action: 'done', date: validDate(parts[1]) };
  const refund = parts[0] === 'refund';
  if (refund) parts.shift();
  if (parts.length < 1 || parts.length > 2) throw new Error(HELP);
  const amount = parts[0].replace(/^\$/, '');
  if (!/^\d{1,7}(\.\d{1,2})?$/.test(amount)) throw new Error('Use a positive dollar amount with no more than two decimal places. For refunds, use /spend refund 5.');
  const [whole, fraction = ''] = amount.split('.');
  const cents = Number(whole) * 100 + Number(fraction.padEnd(2, '0'));
  if (cents <= 0 || cents > 100000000) throw new Error('Amount must be more than $0 and no more than $1,000,000.');
  return { action: 'add', amount_cents: refund ? -cents : cents, category_id: 'coffee', date: validDate(parts[1]) };
}
function validDate(value) {
  if (!value) return null;
  if (!/^\d{4}-\d{2}-\d{2}$/.test(value) || !Number.isFinite(Date.parse(value)) || new Date(value + 'T12:00:00Z').toISOString().slice(0, 10) !== value) throw new Error('Use a real date in YYYY-MM-DD format.');
  return value;
}

async function verifySlack(body, timestamp, signature, secret, now = Date.now()) {
  if (!secret || !/^\d+$/.test(timestamp || '') || Math.abs(now / 1000 - Number(timestamp)) > 300 || !/^v0=[a-f0-9]{64}$/.test(signature || '')) return false;
  const key = await crypto.subtle.importKey('raw', new TextEncoder().encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['verify']);
  const bytes = Uint8Array.from(signature.slice(3).match(/../g), hex => parseInt(hex, 16));
  return crypto.subtle.verify('HMAC', key, bytes, new TextEncoder().encode(`v0:${timestamp}:${body}`));
}

function safeResponseUrl(value) {
  try { const url = new URL(value); return url.protocol === 'https:' && url.hostname === 'hooks.slack.com' && !url.username && !url.password && !url.port && url.pathname.startsWith('/commands/'); } catch { return false; }
}

// Plain text: the Slack handler disables markup so member names cannot ping people.
function formatStandings({ today, ends_on, members }) {
  const dollars = cents => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(cents / 100);
  const final = today > ends_on;
  const eligible = member => final ? member.reviewed_through === ends_on : Boolean(member.reviewed_through);
  const rows = [...members].sort((a, b) => a.total_cents - b.total_cents || a.display_name.localeCompare(b.display_name));
  const ranked = rows.filter(eligible);
  const lines = rows.slice(0, 20).map(member => {
    const rank = eligible(member) ? '#' + (ranked.filter(other => other.total_cents < member.total_cents).length + 1) : 'Unconfirmed';
    const name = member.display_name.replace(/[\r\n\t\u0000-\u001f\u007f]/g, ' ').slice(0, 40);
    const review = member.reviewed_through ? 'reviewed through ' + member.reviewed_through : 'not yet reviewed';
    return `${rank} · ${name} — ${dollars(member.total_cents)} · ${member.entry_count} entries · ${review}`;
  });
  return [
    `October Club — ${final ? 'final' : 'reported'} standings`,
    `Coffee shop · USD · as of ${today} (New York)`,
    `Group total: ${dollars(rows.reduce((sum, member) => sum + member.total_cents, 0))} · ${rows.length} members`,
    '', ...lines,
    ...(rows.length > 20 ? [`Showing 20 of ${rows.length} members; see the website for everyone.`] : []),
    '',
    final ? 'Final ranks require review through ' + ends_on + '. Equal totals tie.' : 'Lowest spending wins. Ranks require a review; compare review dates for missing spending. Equal totals tie.',
    'https://micahtil.github.io/october-club/',
  ].join('\n');
}


const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { 'Content-Type': 'application/json', 'Cache-Control': 'no-store' } });
const reply = (text: string, shareInChannel = false) => ({ response_type: shareInChannel ? 'in_channel' : 'ephemeral', text: text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'), mrkdwn: false, replace_original: false });

Deno.serve(async (request: Request) => {
  if (request.method !== 'POST') return new Response('Method not allowed', { status: 405 });
  if (!request.headers.get('content-type')?.startsWith('application/x-www-form-urlencoded')) return new Response('Unsupported content type', { status: 415 });
  const signingSecret = Deno.env.get('SLACK_SIGNING_SECRET');
  const teamId = Deno.env.get('SLACK_TEAM_ID');
  const appId = Deno.env.get('SLACK_APP_ID');
  const serviceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');
  const supabaseUrl = Deno.env.get('SUPABASE_URL');
  if (!signingSecret || !teamId || !appId || !serviceKey || !supabaseUrl) return json({ error: 'App configuration is incomplete.' }, 503);
  if (Number(request.headers.get('content-length') || 0) > 16000) return new Response('Request too large', { status: 413 });
  const body = await request.text();
  if (body.length > 16000) return new Response('Request too large', { status: 413 });
  if (!await verifySlack(body, request.headers.get('x-slack-request-timestamp'), request.headers.get('x-slack-signature'), signingSecret)) return new Response('Invalid Slack signature', { status: 401 });
  const params = new URLSearchParams(body);
  if (params.get('team_id') !== teamId || params.get('api_app_id') !== appId || params.get('command') !== '/spend') return new Response('Wrong workspace or app', { status: 403 });
  const responseUrl = params.get('response_url') || '';
  const triggerId = params.get('trigger_id');
  const userId = params.get('user_id');
  if (!safeResponseUrl(responseUrl) || !triggerId || triggerId.length > 160 || !/^[UW][A-Z0-9]+$/.test(userId || '')) return json(reply('Slack did not supply a valid request. Please try again.'));
  let command;
  try { command = parseCommand(params.get('text') || ''); } catch (error) { return json(reply(error instanceof Error ? error.message : HELP)); }
  if (command.action === 'help') return json(reply(HELP));
  const { action, ...payload } = command;

  // Acknowledge immediately; Slack allows only 3 seconds. Send the actual outcome
  // to its signed, validated response URL. Only successful standings are shared
  // with the originating channel; acknowledgements and errors remain private.
  const task = (async () => {
    const supabase = createClient(supabaseUrl, serviceKey, { auth: { persistSession: false, autoRefreshToken: false } });
    let text: string;
    let shareInChannel = false;
    try {
      const { data, error } = await supabase.rpc('club_slack_command', { p_team_id: teamId, p_user_id: userId, p_action: action, p_data: payload, p_request_id: triggerId });
      text = error ? error.message : action === 'standings' ? formatStandings(data) : data.message;
      shareInChannel = !error && action === 'standings';
    } catch { text = 'I could not confirm the result. Check /spend total or the website before resubmitting, to avoid a duplicate.'; }
    try {
      const response = await fetch(responseUrl, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(reply(text, shareInChannel)), signal: AbortSignal.timeout(10000) });
      if (!response.ok) console.error('Slack confirmation could not be delivered:', response.status);
    } catch { console.error('Slack confirmation delivery failed; spending may already be recorded.'); }
  })();
  EdgeRuntime.waitUntil(task);
  return json(reply('Processing your command… Your confirmation will appear here shortly.'));
});
